### ISSUE TITLE
App Halted

### ISSUE THREAD

**Issue by Ligmon** [vitaliy-paliy/Messenger#22]
After setup the Firebase, successfully build the project, app will be halted after these pages. How to figure it out? Is that related to the Firebase read/write right?

![截屏2022-03-14 下午6 36 54](https://user-images.githubusercontent.com/101404432/158156199-354f933b-193f-4bd0-8cf2-033bdfc4daa1.png)

![截屏2022-03-14 下午6 37 26](https://user-images.githubusercontent.com/101404432/158156297-17de6c0d-6642-455d-8062-d838e05c71f9.png)

**Comment by Ligmon** [comment]
App will stay in the page as below
![截屏2022-03-14 下午6 51 00](https://user-images.githubusercontent.com/101404432/158157946-6d8bc0ab-636a-483a-b18a-14853884b3ba.png)

**Comment by Ligmon** [comment]
after rebuild the project and run, it will stay in the following page
![截屏2022-03-14 下午6 56 39](https://user-images.githubusercontent.com/101404432/158159915-29b4db42-06de-4473-bfca-8c4eed4205f8.png)

**Comment by vitaliy-paliy** [comment]
Set Realtime Database rules to:
`
  {
    "rules": {
       ".read": true,
       ".write": true     
    }
  }
`

**Comment by Ligmon** [comment]
> Set Realtime Database rules to:
> `{ "rules": { ".read": true, ".write": true } }`

Thanks for your kind and prompt reply. I have this problem with the following settings:, looking for more of your help

![截屏2022-03-14 下午6 17 22](https://user-images.githubusercontent.com/101404432/158289798-b88f507d-a5b9-41e2-a022-b54b39980c8d.png)

**Comment by Ligmon** [comment]
I my self also consider this as a problem of database read/write. So where can I got some check points or dash board in Firebase that can help me to locate the problem? thanks for you prompt reply

**Comment by vitaliy-paliy** [comment]
I think this was the issue that didn't allow you to sign up. If that didn't help, try enabling [Email/Password authentication method](https://firebase.google.com/docs/auth/web/password-auth).

**Comment by Ligmon** [comment]
I still need more help, thanks in advance...The Email/Password authentication has been enabled as below. I am so looking to figure this out.

![截屏2022-03-15 下午6 10 56](https://user-images.githubusercontent.com/101404432/158355714-324861d2-0d86-4f0a-9cbf-514633308afc.png)
![截屏2022-03-15 下午6 11 10](https://user-images.githubusercontent.com/101404432/158355743-51c91a53-ded1-4418-8ddf-66ba81028def.png)

**Comment by Ligmon** [comment]
I mean problem still there if enabled the Email/Password authentication.

**Comment by Ligmon** [comment]
Is it related to the content of pod file? The sentence to specify iOS version is deleted. So the pod is on iOS 13.2 instead of 9.0

**Comment by vitaliy-paliy** [comment]
Try reinstalling the project and follow all of the installation prompts carefully.

**Comment by xoojulian** [comment]
@Ligmon Hi, I've met the same problem. Actually, you need to modify the Storage Rule to the following. You can monitor denied operation in the Usage section of the Firebase console.
`
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
`
@vitaliy-paliy I have followed the README but it seems that in the Storage section, there's no instruction about permission/rule setting.

**Comment by linhnguyen9988** [comment]
> @Ligmon Hi, I've met the same problem. Actually, you need to modify the Storage Rule to the following. You can monitor denied operation in the Usage section of the Firebase console.
> `rules_version = '2'; service firebase.storage { match /b/{bucket}/o { match /{allPaths=**} { allow read, write: if true; } } }`
> @vitaliy-paliy I have followed the README but it seems that in the Storage section, there's no instruction about permission/rule setting.

edit your Storage Rule to the following
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
